# -*- coding: utf-8 -*-
"""Calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13T3uVfyssPikvkhTApgnQxDI5Kdl-p4o

#CALCULADORA
##Vamos cálcular!

Rotina para cáculo
"""

ir_calc = "s"
novo = ""
texto_fim = ".."
prim_valor = 0
seg_valor = 0

print("CALCULADORA SIMPLES! \n")                              # Apresentação do sistema

while (ir_calc == "s") or (ir_calc == "S"):
  print(f"\nDeseja realizar um {novo}cálculo?")               # {novo} caso já tenha sido feito o primeior cálculo
  ir_calc = input("Insira (s) para continuar: ")

  if (ir_calc != "s") and (ir_calc != "S"):
    print(f"\nFim dos trabalhos.{texto_fim}")                 # {texto_fim} para uma melhor interação com o usuário
    break

  novo = "novo "
  texto_fim = "\nObrigado por utilizar este serviço.\nTenha um excelente dia!!!"
  prim_valor = float(input("\nInsira o primeiro valor: "))
  seg_valor = float(input("Insira o segundo valor: "))

  print("\nSoma: ", prim_valor + seg_valor)
  print("Subtração: ", prim_valor - seg_valor)
  if seg_valor != 0:
    print("Divisão: ", prim_valor / seg_valor)
  else:
    print("Divisão: Erro (Divisão por zero)")
  print("Multiplicação: ", prim_valor * seg_valor)